### ISSUE TITLE
textx.model.ObjCrossRef not resolved to proper object

### ISSUE THREAD

**Issue by zilakmarian** [textX/textX#34] opened 2017-05-29 13:44 UTC
I was trying textx and there seems to be a problem with link rule references. Resulting model is containing textx.model.ObjCrossRef instead of specified objects.

Here is an example code:

```python
from textx.metamodel import metamodel_from_file, metamodel_from_str

grammar_str = """
Expression:
    atts+=Attribute[','] 'formula' form=Formula
 ;
Formula:
    (values=FormulaExp (values=AndOr values=FormulaExp)*)
;


FormulaExp:
    ( values=BOOL )
    | ( values=Cond )
    | ( values='(' values=Formula values=')' )
;

Cond:
    negative?='not' (attribute = [Attribute|attr_id])
    ((operator = BinOp values=STRING) | (operator = 'in' '(' values+=STRING[','] ')') | (operator = 'between' values=STRING 'and' values=STRING))
;

attr_id:
    /attr_[a-f0-9]+/
;

Attribute:
    name = attr_id
;

BinOp:
    '<' | '>'   
;

AndOr:
    'and'|'or'
;
"""

mm = metamodel_from_str(grammar_str, ignore_case=True, auto_init_attributes=False)
m = mm.model_from_str("attr_123, attr_444 formula attr_123 < 'aa'")
print m.atts
print m.form.values[0].values[0].attribute
print m.form.values[0].values[0].attribute.cls, m.form.values[0].values[0].attribute.obj_name
```

Second print should be of class Attribute with name _attr_123_. It is ObjCrossRef instead.

**Comment by igordejanovic** [comment] 2017-06-02 13:07
Following part of the grammar has caused the problem:
```
    | ( values='(' values=Formula values=')' )
```
As strings are collected in `values` attribute textX will deduce this attribute to be a list of strings and will not descend into resolving. In this particular grammar parentheses are just a syntax noise and should not be collected at all.

So, the following works:
```
 | ( '(' values=Formula ')' )
```
Note that `values` will be now correctly recognized as a single value (i.e. not a list) as there is only one object collected in each alternative.

Nevertheless, I would like this particular case of collecting arbitrary objects in a single rule to be either possible or to raise en error. At present time I think it wouldn't be that hard to enable. The only difficulty I see will be the visualization (export to dot). Probably the most pragmatic solution in visualization is to report such type as a list of objects and display it inline.

**Comment by igordejanovic** [comment] 2017-06-02 17:00
The issue is fixed on the master branch. Please test.

**Closed as completed** 2017-06-14 15:15 UTC
Labels: bug
