### ISSUE TITLE
$ doesn't swallow the '\n' if skipws=False

### ISSUE THREAD

**Issue by wryun** [textX/textX#207] opened 2019-09-16 12:13 UTC
e.g.

```
Comment: /[ ]*#.*\n/;
```

behaves differently to:
```
Comment: /[ ]*#.*$/;
```

I think it's more natural if they're equivalent.

**Comment by goto40** [comment] 2019-09-18 19:42
Thank you for the report. First, I was intuitively convinced by the observation to be a bug. But playing around with the re-module made me look up the documentation:

I think this is not a bug. As stated in [python docs for the re-module](https://docs.python.org/3/library/re.html)
> $
>    Matches the end of the string or just **before the newline** at the end of the string, and in MULTILINE mode also matches before a newline. [...] **searching for a single $** in 'foo\n' **will find two (empty) matches**: one just before the newline, and one at the end of the string.

 * Changing the functionality of textx-grammars to consume a newline with "$" would break with the re-module specification.
 * On the other hand a '\n' must - of course - consume the newline.

Thus, I suggest to leave the functionality as it is... To be discussed.

**Comment by igordejanovic** [comment] 2019-09-19 06:25
@goto40 thanks for the analysis. I agree. `$` acts as an anchor to the end of the line similarly to `^` that act as an anchor to the beginning. Thus, `\n` should be consumed explicitly.
First example above should leave `\n` unconsumed.

I'm closing this as resolved. If anyone thinks this is a problem we can reopen and discuss.

**Closed as completed by igordejanovic** 2019-09-19 06:25 UTC
